language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  # 6.x
  # 6.x-1.x
  - GITHUB_REPOSITORY=drupal-botcha DRUPAL_VERSION=6.x PROFILE=default DRUPAL_MODULE=botcha BRANCH=1.x
  # (obsolete) 6.x-2.x
  #- GITHUB_REPOSITORY=drupal-botcha DRUPAL_VERSION=6.x PROFILE=default DRUPAL_MODULE=botcha BRANCH=2.x
  # 6.x-3.x
  - GITHUB_REPOSITORY=drupal-botcha DRUPAL_VERSION=6.x PROFILE=default DRUPAL_MODULE=botcha BRANCH=3.x
  # 6.x-4.x
  - GITHUB_REPOSITORY=drupal-botcha DRUPAL_VERSION=6.x PROFILE=default DRUPAL_MODULE=botcha BRANCH=4.x
  # 7.x
  # 7.x-1.x
  - GITHUB_REPOSITORY=drupal-botcha DRUPAL_VERSION=7.x PROFILE=standard DRUPAL_MODULE=botcha BRANCH=1.x
  # (obsolete) 7.x-2.x
  #- GITHUB_REPOSITORY=drupal-botcha DRUPAL_VERSION=7.x PROFILE=standard DRUPAL_MODULE=botcha BRANCH=2.x
  # 7.x-3.x
  - GITHUB_REPOSITORY=drupal-botcha DRUPAL_VERSION=7.x PROFILE=standard DRUPAL_MODULE=botcha BRANCH=3.x
  # 7.x-4.x
  - GITHUB_REPOSITORY=drupal-botcha DRUPAL_VERSION=7.x PROFILE=standard DRUPAL_MODULE=botcha BRANCH=4.x

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush-devel
 - phpenv rehash
 - cd ..
 # Prepare Drupal.
 - mkdir drupal
 - cd drupal
 - cp ../$GITHUB_REPOSITORY/$DRUPAL_VERSION/drupal.make drupal.make
 - drush make drupal.make .
 # Discover newly downloaded directory.
 - ls -la
 # Install Drupal.
 - drush si $PROFILE --db-url=mysql://root:@localhost/drupal --yes
 # Prepare Simpletest.
 - sh -c "if [ '$DRUPAL_VERSION' = '6.x' ]; then cp sites/all/modules/simpletest/run-tests.sh scripts/run-tests.sh; fi"
 - drush en simpletest --yes
 # Prepare required modules.
 - cp ../$GITHUB_REPOSITORY/$DRUPAL_VERSION/$BRANCH/$DRUPAL_MODULE.make $DRUPAL_MODULE.make
 - drush make $DRUPAL_MODULE.make . --no-core
 # Prepare the module.
 # No need: it is done recursively by drush make.
 #- drush make sites/all/modules/$DRUPAL_MODULE/$DRUPAL_MODULE.make . --no-core
 # Drush in D6 doesn't handle dependencies right.
 - sh -c "if [ '$DRUPAL_VERSION' = '7.x' ]; then drush en $DRUPAL_MODULE --yes; else drush php-eval \"module_enable('$DRUPAL_MODULE');\"; fi"
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 #- drush vset simpletest_verbose FALSE --yes
 - drush vset simpletest_verbose TRUE --yes
 # Create a directory to output results.
 - mkdir results

script: php scripts/run-tests.sh --php ~/.phpenv/versions/5.4.16/bin/php --url 'http://127.0.0.1:8080' --verbose --file sites/all/modules/$DRUPAL_MODULE/tests/$DRUPAL_MODULE.test
 #drush test-run --xml --file=sites/all/modules/moopapi/core/simpletest.test --uri=http://127.0.0.1:8080

after_script:
 - cd results
 - ls -la
# Trigger testing of changes at drupal.org
